### ISSUE TITLE
This project is still going on?

### ISSUE THREAD

**Issue by iamcyw** [patternfly-kotlin/patternfly-fritz2#79]
Excuse me, this project has not been updated for a long time, is it continuing to develop?

**Comment by hpehl** [comment]
Yes, it is 😉
But you're right, the last update was quite a long time ago. I'm currently busy with lots of other tasks, but definitely want to continue work on patternfly-fritz2. It just might take some time. So please stay tuned! 

And remember: contributions are always welcome!

**Comment by iamcyw** [comment]
I am new to js and kotlin but would like to use patternfly-kolin in my new project.
lately I have also been researching and implementing some needed components but it is overwhelming for me. I don't know how to do it successfully😔

**Comment by hpehl** [comment]
No worries. Take your time and try to take a look at the code and the examples.
